### ISSUE TITLE
analogRead always returns 806 instead of 1023

### ISSUE THREAD

**Issue by gintsmurans** [Controllino/ControllinoLibrary#3]
![image](https://cloud.githubusercontent.com/assets/56369/13213491/ffb88d84-d951-11e5-8b6a-6d541486cb79.png)

This is example found here: https://raw.githubusercontent.com/Controllino/ControllinoLibrary/master/Examples/Controllino_Example/Controllino_Example.ino

A0 should read 0 and 1023 (its connected to D0 pin), but instead it reads 0 and 806. Is there anything wrong with the voltage reference or am I missing something? Btw, power supply is 24 volts.

**Comment by SG-Tronic** [comment]
Hello,
this is cause by the fact that Controllino actually doesnt have maximum of 24V . The maximum for 24V setting is close to 30V. So value 1023 will be returned when you would get close to 30V power supply.

**Comment by gintsmurans** [comment]
Hmm, using analogReference (https://www.arduino.cc/en/Reference/AnalogReference) didn't help either, so how can we correctly measure analog read values? I will though test this a little more when next controllino arrives.
