### ISSUE TITLE
Digital 20 - Digital 23 mapping

### ISSUE THREAD

**Issue by therealstan** [Controllino/ControllinoLibrary#4]
Pins Digital 20 - Digital 23 seem not to be implemented to use with digitalWrite, from Arduino lib.

Is it possible to use those pins with your library? I understand, that these pins don't have an according alias on arduino, but still. 

I would really like to somehow circumvent using this syntax in order to set Digital 20.

```
PORTD = B11110111 
```

**Comment by ControllinoAdmin** [comment]
Hi Stanislav,



yes, you are right. Our library does not support these digital outputs as we have tried to do not touch Arduino Core functionality.

But it may be a point for further releases...



I am afraid that you have to use this "PORTD" way to control these pins.



Please check File-Examples->Controllino Library->Examples->Controllino_Example in the Arduino IDE for more details.



Thanks,

Best regards,

Lukas



-----Original message-----
