### ISSUE TITLE
Controllino 1.0.3 not showing with arduino IDE 1.6.12

### ISSUE THREAD

**Issue by smcardle** [Controllino/ControllinoLibrary#5]
Hi Everybody

Loading the Controllino Library into the Arduino 1.6.12 IDE does not show up the Controllino boards on the board types list.

Regards

Steve

**Comment by ControllinoAdmin** [comment]
Hi Steve,



you also need to install the "Controllino Hardware" by the Boards Manager.



Please, follow the instructions described here

https://controllino.biz/wp-content/uploads/2016/04/Detailed-STEP-BY-STEP-GUIDE-FOR-CONTROLLINO-INSTALLATION.pdf



Best regards,

Lukas







-----Original message-----
